[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Next.js specific settings for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# File upload optimization (Netlify allows larger files than Vercel)
[build.processing]
  skip_processing = false# Clean build trigger Fri Sep  5 16:30:38 NZST 2025
