[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Next.js specific settings for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function configuration for API routes
[functions]
  external_node_modules = ["@supabase/supabase-js"]
  node_bundler = "esbuild"

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API route headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, x-csrf-token"

# File upload optimization (Netlify allows larger files than Vercel)
[build.processing]
  skip_processing = false

# Skip secrets scanning for configuration values that are not actually secrets
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "EMAIL_PROVIDER,EMAIL_FROM_NAME,EMAIL_FROM_ADDRESS"