// Static version - generated at build time for Vercel deployment
// This file is auto-generated by scripts/generate-static-version.js

export const STATIC_VERSION = {
  major: 1,
  month: 8,
  day: 21,
  build: 34,
  alpha: '',
  buildDate: '2025-08-21',
  timestamp: 1755768423700
}

export const getStaticVersion = () => {
  const { major, month, day, build, alpha } = STATIC_VERSION
  return `v${major}.${month}.${day}.${String(build).padStart(3, '0')}${alpha}`
}
