// Static version - generated at build time for Netlify deployment
// This file is auto-generated by scripts/generate-static-version.js

export const STATIC_VERSION = {
  major: 1,
  month: 10,
  day: 1,
  build: 12,
  alpha: '',
  buildDate: '2025-10-01',
  timestamp: 1759313841027
}

export const getStaticVersion = () => {
  const { major, month, day, build, alpha } = STATIC_VERSION
  return `v${major}.${month}.${day}.${String(build).padStart(3, '0')}${alpha}`
}
