// Static version - generated at build time for Netlify deployment
// This file is auto-generated by scripts/generate-static-version.js

export const STATIC_VERSION = {
  major: 1,
  month: 9,
  day: 30,
  build: 10,
  alpha: '',
  buildDate: '2025-09-30',
  timestamp: 1759196002711
}

export const getStaticVersion = () => {
  const { major, month, day, build, alpha } = STATIC_VERSION
  return `v${major}.${month}.${day}.${String(build).padStart(3, '0')}${alpha}`
}
